version: 2

references:
  restore_homebrew_cache: &restore_homebrew_cache
    restore_cache:
      keys:
        - v3-homebrew-cache-{{ arch }}-{{ .Branch }}
        - v3-homebrew-cache-{{ arch }}
  save_homebrew_cache: &save_homebrew_cache
    save_cache:
      key: v3-homebrew-cache-{{ arch }}-{{ .Branch }}
      paths:
        - /usr/local/Cellar
        - /usr/local/Homebrew
        - ~/Library/Logs/Homebrew

jobs:
  test:
    macos:
      xcode: "9.3.1"

    steps:
      - checkout
      - *restore_homebrew_cache
      - run: brew update
      - run: brew install shellcheck
      - run: brew link shellcheck
      - run: brew outdated shellcheck || brew upgrade shellcheck
      - *save_homebrew_cache
      - run: rake test
      - run: rm -f /usr/local/bin/circleci
      - run: echo "export CHSH=no" >> $BASH_ENV
      - run: source $BASH_ENV
      - run: sh -x bootstrap.sh
      - run: sh -x bin/mobile-setup.sh

workflows:
  version: 2
  test:
    jobs:
      - test
