version: 2

references:
  restore_homebrew_cache: &restore_homebrew_cache
    restore_cache:
      keys:
        - v3-homebrew-cache-{{ arch }}-{{ .Branch }}
        - v3-homebrew-cache-{{ arch }}
  save_homebrew_cache: &save_homebrew_cache
    save_cache:
      key: v3-homebrew-cache-{{ arch }}-{{ .Branch }}
      paths:
        - /usr/local/Cellar
        - /usr/local/Homebrew
        - ~/Library/Logs/Homebrew

jobs:
  build:
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - *restore_homebrew_cache
      - run: brew update
      - run: brew install shellcheck
      - run: brew link shellcheck
      - run: brew outdated shellcheck || brew upgrade shellcheck
      - *save_homebrew_cache
      - run: shellcheck seed-workstation.sh -e SC2039
      - run: ls -l /usr/local/bin/circleci
      - run: rm /usr/local/bin/circleci
      - run: sh seed-workstation.sh
