version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"

    steps:
      - checkout
      - run: brew update
      - run: brew install shellcheck
      - run: shellcheck seed-workstation.sh -e SC2039
      - run: sh seed-workstation.sh
